---
- name: Copy backend files
  become: true
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: Start PM2
  become: true
  shell: |
    cd /home/ubuntu/
    tar xzvf artifact.tar.gz
    # mv home/circleci/project/backend .
    cd backend
    npm install
    npm run build
    pm2 start npm -- start